server:
  port: ${SB_CONFIG_PORT}

spring:
  boot:
    admin:
      client:
        url: http://${SB_CONFIG_HOST}:${SB_CONFIG_PORT}
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configs
  profiles:
    active: native
  security:
    user:
      name: ${SB_CONFIG_USER}
      password: ${SB_CONFIG_PASSWORD}
