server:
  port: ${SB_DEPOSIT_PORT}

logging.level:
    ru.veqveq.dictionary: DEBUG
    ru.veqveq.core: DEBUG

spring:
  jpa:
    properties:
      hibernate:
        default_schema: ${SB_DEPOSIT_SCHEMA}
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
    default-schema: ${spring.jpa.properties.hibernate.default_schema}
    parameters:
      schema: ${spring.jpa.properties.hibernate.default_schema}

app:
  scheduled:
    check-calculated-day: "0 0 0 * * ?"
  free-cash-history:
    script-file: classpath:db/sql/get_free_cash_history.sql